name: Java CI to create and upload release on pull request
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - run: mvn clean install -DskipTests
      - run: mkdir staging && cp amqp10-transport/target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
          retention-days: 1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.run_number }}"
          title: "Build ${{ github.run_number }}"
          prerelease: false
          files: staging/*.jar